### ISSUE TITLE
import Alamofire error

### ISSUE THREAD

**Issue by pfoster** [cashierfu/CashierFu#2]
It's still doing the weird thing where it builds, but then tells me it can't import Alamofire.

**Comment by acwright** [comment]
Have you tried nuking the DerivedData folder? ~/Library/Developer/Xcode/DerivedData

**Comment by pfoster** [comment]
Yeah. I nuked derived data, I cleaned, and I cleaned the build folder.

**Comment by pfoster** [comment]
It seems like it's working, though the code I got from paw appears to be for an old version of alamofire or something, so I haven't gotten it working yet, but it is recognizing methods that come from alamofire, I think.

**Comment by acwright** [comment]
I'm going to work on the adapter for a minute or two. So stay away from that file just for a bit. Hopefully I can come up with something working. Big issues I forgot about is that we need to authenticate the account first before making requests in the adapter.
