### ISSUE TITLE
Sign in

### ISSUE THREAD

**Issue by pfoster** [cashierfu/CashierFu#4]
I attempted to use CFKAccount.signInWithEmail() in the playground. It isn't working for me, though. Not sure if it still needs work or if I'm using it wrong.

**Comment by pfoster** [comment]
I just pushed my attempt

**Comment by acwright** [comment]
Yep. It should at least call /v1/oauth/token and get an access token but it doesn't yet convert that to a CFKAccount. I'm needing to add to the API some way to fetch an Account using the access token.
