### ISSUE TITLE
Computed properties on models should be asynchronous

### ISSUE THREAD

**Issue by acwright** [cashierfu/CashierFu#7]
The computed properties on models need to be asynchronous or they will never return anything other than 0. For example (from CFKCustomer):

    /// The balance on the account in pennies
    public var balance: Int {
        var adjustments = [CFKAdjustment]()
        var balance = 0
        
        // The call to self.adjustments here is asynchronous. It will not return results until sometime later...
        self.adjustments { (objects, error) -> Void in
            // ... so adjustments will be empty until this closure is executed!
            adjustments = objects as! [CFKAdjustment]
        }
        
        // ... so this code will execute before the above closure is complete meaning adjustments is empty here!
        for CFKAdjustment in adjustments {
            let value = CFKAdjustment.amount as Int
            balance += value
        }
        
        return balance
    }

To solve this problem we will have to make the computed properties on the models take a closure themselves. See the adapter protocol for how to make function that takes a closure.

**Comment by pfoster** [comment]
I took a swing at this. Could you check out **balance** on **CFKCertificate** and see if I've done that right?

**Comment by acwright** [comment]
I think the calculation part looks fine. We need a test case for these to be sure.

The issue is with the adjustments (and other relationship) functions. I removed these from the models because there is no way at the moment to make them work for all adapters. Here is the problem, this line:

`parameters.filters["certificateID"] = self.objectID`

uses `certificateID` which will be fine when using any of the adapters **except** the `CashierFuAdapter`. That adapter expects the filter key to be `certificate-id`. See the problem? So we can't hard code that key into the relationship functions in the models. So for now I want to remove them.

And this also causes a problem with the computed property functions because in order to get the to-many relationships you need to properly form the filter key and again hard coding this string into the function would cause a problem across adapters.

Need to come up with a workaround... thoughts? Here is possibilities I have though of:

1. Pass the relationship key into the function. This sounds messy but would work...
2. Add something to CFKParameterSet or CFKDatabaseAdapter that could "translate" the key to correct string for given adapter.

**Comment by acwright** [comment]
Also, looking at your function again it appears it is still not asynchronous. The balance function itself needs to return a closure! I'm going to upload a try in a sec.

**Comment by pfoster** [comment]
Would a global tag or something that sets the adapter type that we use as a parameter be better?

**Comment by pfoster** [comment]
I guess your second solution would probably be something like that.

**Comment by pfoster** [comment]
Could we make another enum that would take the adapter type as an argument for a switch that picks the right string? Or a switch that picks the right enum rather.

**Comment by acwright** [comment]
I have pushed a commit that should fix the issue with ID's. See solution in CFKCertificate. I have added a `belongsTo` property to `CFKParameterSet` that takes a `CFKObject`. This is then passed into the adapter and the adapter looks up the `objectType` property from the object and forms the proper key string.
